FROM rust:alpine
RUN apk add --update --no-cache \
	curl \
	g++ \
	gcc \
	git \
	libxml2-dev \
	libxslt-dev \
	make \
	ncurses-dev \
	openssl-dev \
	nano

RUN apk add --update openssl && \
    rm -rf /var/cache/apk/*

RUN apk add --update --no-cache alpine-sdk bash
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
CMD ["/bin/sh -c"]


