// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.21.8
// source: balistic-engine/gRPC.proto

package balistic

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalisticRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Velocity float32 `protobuf:"fixed32,1,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Angle    float32 `protobuf:"fixed32,2,opt,name=angle,proto3" json:"angle,omitempty"`
	Height   float32 `protobuf:"fixed32,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *BalisticRequest) Reset() {
	*x = BalisticRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balistic_engine_gRPC_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalisticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalisticRequest) ProtoMessage() {}

func (x *BalisticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balistic_engine_gRPC_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalisticRequest.ProtoReflect.Descriptor instead.
func (*BalisticRequest) Descriptor() ([]byte, []int) {
	return file_balistic_engine_gRPC_proto_rawDescGZIP(), []int{0}
}

func (x *BalisticRequest) GetVelocity() float32 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

func (x *BalisticRequest) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *BalisticRequest) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type BalisticResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxDistance float32 `protobuf:"fixed32,1,opt,name=max_distance,json=maxDistance,proto3" json:"max_distance,omitempty"`
	MaxHeight   float32 `protobuf:"fixed32,2,opt,name=max_height,json=maxHeight,proto3" json:"max_height,omitempty"`
	Time        float32 `protobuf:"fixed32,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *BalisticResponse) Reset() {
	*x = BalisticResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balistic_engine_gRPC_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalisticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalisticResponse) ProtoMessage() {}

func (x *BalisticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balistic_engine_gRPC_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalisticResponse.ProtoReflect.Descriptor instead.
func (*BalisticResponse) Descriptor() ([]byte, []int) {
	return file_balistic_engine_gRPC_proto_rawDescGZIP(), []int{1}
}

func (x *BalisticResponse) GetMaxDistance() float32 {
	if x != nil {
		return x.MaxDistance
	}
	return 0
}

func (x *BalisticResponse) GetMaxHeight() float32 {
	if x != nil {
		return x.MaxHeight
	}
	return 0
}

func (x *BalisticResponse) GetTime() float32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balistic_engine_gRPC_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_balistic_engine_gRPC_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_balistic_engine_gRPC_proto_rawDescGZIP(), []int{2}
}

type HelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyMessage string `protobuf:"bytes,1,opt,name=my_message,json=myMessage,proto3" json:"my_message,omitempty"`
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balistic_engine_gRPC_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balistic_engine_gRPC_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_balistic_engine_gRPC_proto_rawDescGZIP(), []int{3}
}

func (x *HelloResponse) GetMyMessage() string {
	if x != nil {
		return x.MyMessage
	}
	return ""
}

var File_balistic_engine_gRPC_proto protoreflect.FileDescriptor

var file_balistic_engine_gRPC_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x62, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x62, 0x61,
	0x6c, 0x69, 0x73, 0x74, 0x69, 0x63, 0x22, 0x5b, 0x0a, 0x0f, 0x42, 0x61, 0x6c, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x6c,
	0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x76, 0x65, 0x6c,
	0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x22, 0x68, 0x0a, 0x10, 0x42, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x5f, 0x64,
	0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x6d,
	0x61, 0x78, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61,
	0x78, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09,
	0x6d, 0x61, 0x78, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x07, 0x0a,
	0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2e, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x79, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x79, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x8c, 0x01, 0x0a, 0x0f, 0x42, 0x61, 0x6c, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x09, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x62, 0x61, 0x6c, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x2e, 0x42, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x62, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x42, 0x61,
	0x6c, 0x69, 0x73, 0x74, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x33, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x0f, 0x2e, 0x62, 0x61, 0x6c, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x62, 0x61, 0x6c,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1e, 0x5a, 0x1c, 0x62, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x62, 0x61, 0x6c,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_balistic_engine_gRPC_proto_rawDescOnce sync.Once
	file_balistic_engine_gRPC_proto_rawDescData = file_balistic_engine_gRPC_proto_rawDesc
)

func file_balistic_engine_gRPC_proto_rawDescGZIP() []byte {
	file_balistic_engine_gRPC_proto_rawDescOnce.Do(func() {
		file_balistic_engine_gRPC_proto_rawDescData = protoimpl.X.CompressGZIP(file_balistic_engine_gRPC_proto_rawDescData)
	})
	return file_balistic_engine_gRPC_proto_rawDescData
}

var file_balistic_engine_gRPC_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_balistic_engine_gRPC_proto_goTypes = []interface{}{
	(*BalisticRequest)(nil),  // 0: balistic.BalisticRequest
	(*BalisticResponse)(nil), // 1: balistic.BalisticResponse
	(*Empty)(nil),            // 2: balistic.Empty
	(*HelloResponse)(nil),    // 3: balistic.HelloResponse
}
var file_balistic_engine_gRPC_proto_depIdxs = []int32{
	0, // 0: balistic.BalisticService.Calculate:input_type -> balistic.BalisticRequest
	2, // 1: balistic.BalisticService.Hello:input_type -> balistic.Empty
	1, // 2: balistic.BalisticService.Calculate:output_type -> balistic.BalisticResponse
	3, // 3: balistic.BalisticService.Hello:output_type -> balistic.HelloResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_balistic_engine_gRPC_proto_init() }
func file_balistic_engine_gRPC_proto_init() {
	if File_balistic_engine_gRPC_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_balistic_engine_gRPC_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalisticRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_balistic_engine_gRPC_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalisticResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_balistic_engine_gRPC_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_balistic_engine_gRPC_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_balistic_engine_gRPC_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_balistic_engine_gRPC_proto_goTypes,
		DependencyIndexes: file_balistic_engine_gRPC_proto_depIdxs,
		MessageInfos:      file_balistic_engine_gRPC_proto_msgTypes,
	}.Build()
	File_balistic_engine_gRPC_proto = out.File
	file_balistic_engine_gRPC_proto_rawDesc = nil
	file_balistic_engine_gRPC_proto_goTypes = nil
	file_balistic_engine_gRPC_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BalisticServiceClient is the client API for BalisticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BalisticServiceClient interface {
	Calculate(ctx context.Context, in *BalisticRequest, opts ...grpc.CallOption) (*BalisticResponse, error)
	Hello(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HelloResponse, error)
}

type balisticServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBalisticServiceClient(cc grpc.ClientConnInterface) BalisticServiceClient {
	return &balisticServiceClient{cc}
}

func (c *balisticServiceClient) Calculate(ctx context.Context, in *BalisticRequest, opts ...grpc.CallOption) (*BalisticResponse, error) {
	out := new(BalisticResponse)
	err := c.cc.Invoke(ctx, "/balistic.BalisticService/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balisticServiceClient) Hello(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/balistic.BalisticService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalisticServiceServer is the server API for BalisticService service.
type BalisticServiceServer interface {
	Calculate(context.Context, *BalisticRequest) (*BalisticResponse, error)
	Hello(context.Context, *Empty) (*HelloResponse, error)
}

// UnimplementedBalisticServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBalisticServiceServer struct {
}

func (*UnimplementedBalisticServiceServer) Calculate(context.Context, *BalisticRequest) (*BalisticResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (*UnimplementedBalisticServiceServer) Hello(context.Context, *Empty) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}

func RegisterBalisticServiceServer(s *grpc.Server, srv BalisticServiceServer) {
	s.RegisterService(&_BalisticService_serviceDesc, srv)
}

func _BalisticService_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalisticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalisticServiceServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/balistic.BalisticService/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalisticServiceServer).Calculate(ctx, req.(*BalisticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalisticService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalisticServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/balistic.BalisticService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalisticServiceServer).Hello(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _BalisticService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "balistic.BalisticService",
	HandlerType: (*BalisticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _BalisticService_Calculate_Handler,
		},
		{
			MethodName: "Hello",
			Handler:    _BalisticService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "balistic-engine/gRPC.proto",
}
