version: '3.8'
services:

  r-zookeeper:
    image: wurstmeister/zookeeper
    ports:
        - "2181:2181"

  r-kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: r-kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "r-zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "messages:1:1, benchmark_topic_10B:1:1, benchmark_topic_200B:1:1, benchmark_topic_1KB:1:1, benchmark_topic_10KB:1:1, test_topic1:1:1"
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
    volumes:
      - ./volumes/kafka_data/data:/data
      - ./volumes/kafka_data/logs:/logs
      - ./volumes/kafka_data/topics:/kafka
    depends_on:
      - r-zookeeper


  r-redis:
    image: redis:latest
    volumes:
      - ./volumes/redis/data:/data
    ports:
      - 6379:6379

  cqrs:
    image: ayagasha/cqrs:latest